# SPDX-License-Identifier: GPL-2.0
dtbo-$(CONFIG_ARCH_EXYNOS) += \
        s5e9945-erd9945_r03.dtbo	\
        s5e9945-erd9945.dtbo		\
        s5e9945-erd9945_r01.dtbo	\
        s5e9945-erd9945_r02.dtbo	\
        s5e9945_evt0-erd9945.dtbo	\
        s5e9945_s5400-erd9945.dtbo	\
        s5e9945_s6375-erd9945.dtbo

always-y	:= $(dtb-y) $(dtbo-y)
clean-files	:= *.dtb *.dtbo
